apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-proxy-vector-config
  namespace: sen-dev-dev-azr-k8s-sen-w2-001
data:
  vector.yaml: |
    sources:
      nginx_proxy_logs:
        type: kubernetes_logs
        namespaces:
          - sen-dev-dev-azr-k8s-sen-w2-001
        pod_selector:
          match_labels:
            app: nginx-proxy

    transforms:
      format_syslog:
        type: remap
        inputs:
          - nginx_proxy_logs
        source: |
          .message = string!(.message)
          ts = format_timestamp!(now(), format: "%Y-%m-%dT%H:%M:%S.%fZ")
          hostname = get_hostname!()
          . = "<134>1 " + ts + " " + hostname + " nginx-proxy - - - " + .message

    sinks:
      vector_endpoint:
        type: socket
        mode: tcp
        inputs:
          - format_syslog
        address: vector-sandbox.sen-dev-dev-azr-k8s-sen-w2-001:1514
        encoding:
          codec: raw_message
        tls:
          enabled: true
          verify_certificate: false
